baseurl = "https://traveller42.github.com/ogs-notifier"
languageCode = "en-us"
title = "OGS Notifier"
theme = "bootie-docs"
copyright = "Copyright (c) 2016, Clark B. Wierda"

[params]
  description = "Chrome Extension for easy notifications from Online-Go Server"
  mainMenu = ["about", "usage"]
  repositoryUrl = "https://github.com/traveller42/ogs-notifier"
  noCategoryLink = true
